stages:
  - build
  - deploy
  - android

variables:
  GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS

before_script:
  - echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > /tmp/service-account.json
  - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/service-account.json"

image: node:22

cache:
  paths:
    - node_modules/

export_pwa:
  stage: build
  script:
    - npm install
    - npm ci
    - npx expo export --platform web --output-dir dist
  artifacts:
    paths:
      - dist/

deploy_pwa_vercel:
  stage: deploy
  script:
    - vercel deploy dist --yes --prod --token $VERCEL_TOKEN
  dependencies:
    - export_pwa

build_apk:
  stage: android
  image: node:22
  script:
    - npm ci
    - eas build --platform android --profile production --non-interactive --json > result.json
    - |
      APK_URL=$(jq -r '.[0].artifacts.buildUrl' result.json)
      echo "APK URL: $APK_URL"
      curl -L -o app.apk "$APK_URL"
      file app.apk

      if file app.apk | grep -q 'Zip archive data'; then
        echo "Arquivo APK válido."
      else
        echo "Erro: o arquivo baixado não é um APK válido."
        cat app.apk
        exit 1
      fi

    - firebase appdistribution:distribute app.apk --app $FIREBASE_ANDROID_APP_ID --groups "testadores" 

