stages:
  - android
  - build
  - deploy

image: node:22

cache:
  paths:
    - node_modules/

export_pwa:
  stage: build
  script:
    - npm install -g vercel
    - npm ci
    - npx expo export --platform web --output-dir dist
  artifacts:
    paths:
      - dist/

deploy_pwa_vercel:
  stage: deploy
  script:
    - vercel deploy dist --yes --prod --token $VERCEL_TOKEN
  dependencies:
    - export_pwa

build_apk:
  stage: android
  image: node:22
  script:
    - npm install -g eas-cli firebase-tools
    - npm ci
    - eas build --platform android --profile production --non-interactive --json > result.json
    - $APK_URL = (Get-Content result.json | ConvertFrom-Json)[0].artifacts.buildUrl
    - Invoke-WebRequest -Uri $APK_URL -OutFile app.apk
    - firebase appdistribution:distribute app.apk `
    - app $env:FIREBASE_ANDROID_APP_ID `
    - token $env:FIREBASE_CLI_TOKEN `
    - groups "testadores"